<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Admin-PC" name="com.uno.test.technician.Technician_TicketSummaryTest" tests="27" failures="3" timestamp="16 Jan 2019 07:45:24 GMT" time="461.805" errors="1">
  <testcase name="TicketSummaryTab" time="11.511" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="VerifyTotalCountAndStatusOfRequestsOpenTab" time="18.991" classname="com.uno.test.technician.Technician_TicketSummaryTest">
    <error type="org.openqa.selenium.StaleElementReferenceException" message="The element reference of &lt;td&gt; is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;ADMIN-PC&#039;, ip: &#039;192.168.1.16&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_161&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 64.0.2, capabilities: {desiredCapabilities: {acceptInsecureCerts: true, browserName: firefox}}, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 6428, moz:profile: C:\Users\Admin\AppData\Loca..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 6.1, rotatable: false, setWindowRect: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ea4a55b5-0a3b-4200-8f0e-ec79a84eba03">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: The element reference of <td> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ADMIN-PC', ip: '192.168.1.16', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 64.0.2, capabilities: {desiredCapabilities: {acceptInsecureCerts: true, browserName: firefox}}, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 6428, moz:profile: C:\Users\Admin\AppData\Loca..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 6.1, rotatable: false, setWindowRect: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ea4a55b5-0a3b-4200-8f0e-ec79a84eba03
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:489)
at com.uno.baseClass.BaseCode.highLight(BaseCode.java:136)
at com.uno.pages.technician.Technician_TicketSummaryPage.verifyTotalCountAndStatusOfRequestsOpenTab(Technician_TicketSummaryPage.java:78)
at com.uno.test.technician.Technician_TicketSummaryTest.VerifyTotalCountAndStatusOfRequestsOpenTab(Technician_TicketSummaryTest.java:96)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyTotalCountAndStatusOfRequestsOpenTab -->
  <testcase name="TotalCountofAssignedButNoETATab" time="45.598" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfETAExpiredAndNoATATab" time="11.076" classname="com.uno.test.technician.Technician_TicketSummaryTest">
    <failure type="java.lang.AssertionError" message="Count is not match expected [30] but found [34]">
      <![CDATA[java.lang.AssertionError: Count is not match expected [30] but found [34]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.uno.pages.technician.Technician_TicketSummaryPage.totalCountOfETAExpiredAndNoATATab(Technician_TicketSummaryPage.java:162)
at com.uno.test.technician.Technician_TicketSummaryTest.TotalCountOfETAExpiredAndNoATATab(Technician_TicketSummaryTest.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TotalCountOfETAExpiredAndNoATATab -->
  <testcase name="StatusOfETAExpiredAndNoATATab" time="32.807" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="CompareTimeOfETAInETAExpiredAndNoATATab" time="12.257" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="ATAOfETAExpiredAndNoATATab" time="10.108" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfWorkInProgressTab" time="8.008" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="StatusOfWorkInProgressTab" time="11.396" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="ATAOfWorkInProgressTab" time="19.758" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfRequestsPausedTab" time="5.407" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="StatusOfRequestsPausedTab" time="5.062" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfPendingForSparesTab" time="3.864" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfRequestSLAColdTab" time="5.715" classname="com.uno.test.technician.Technician_TicketSummaryTest">
    <failure type="java.lang.AssertionError" message="Count is not match expected [11] but found [17]">
      <![CDATA[java.lang.AssertionError: Count is not match expected [11] but found [17]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.uno.pages.technician.Technician_TicketSummaryPage.totalCountOfRequestSLAColdTab(Technician_TicketSummaryPage.java:527)
at com.uno.test.technician.Technician_TicketSummaryTest.TotalCountOfRequestSLAColdTab(Technician_TicketSummaryTest.java:180)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TotalCountOfRequestSLAColdTab -->
  <testcase name="CompareColdSLAImageOfRequestSLAColdTab" time="6.841" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfRequestSLAHotTab" time="3.539" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="CompareHotSLAImageOfRequestSLAHotTab" time="64.393" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfRequestSLAWarmTab" time="4.448" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="CompareWarmSLAImageOfRequestSLAWarmTab" time="64.166" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfRequestSLANearToViolationTab" time="4.769" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="CompareNearToViolationImageOfRequestSLANearToViolationTab" time="63.258" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfRequestSLAViolatedTab" time="7.720" classname="com.uno.test.technician.Technician_TicketSummaryTest">
    <failure type="java.lang.AssertionError" message="Count is not match expected [31] but found [37]">
      <![CDATA[java.lang.AssertionError: Count is not match expected [31] but found [37]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.uno.pages.technician.Technician_TicketSummaryPage.totalCountOfRequestSLAViolatedTab(Technician_TicketSummaryPage.java:733)
at com.uno.test.technician.Technician_TicketSummaryTest.TotalCountOfRequestSLAViolatedTab(Technician_TicketSummaryTest.java:232)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TotalCountOfRequestSLAViolatedTab -->
  <testcase name="CompareViolatedSLAImageOfRequestSLAViolatedTab" time="8.765" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfConsumedWithSparesTab" time="6.992" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfRequestsClosedByTechnicianTab" time="5.506" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfRequestsFinalClosedTab" time="9.069" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
  <testcase name="TotalCountOfAllRequestsTab" time="10.781" classname="com.uno.test.technician.Technician_TicketSummaryTest"/>
</testsuite> <!-- com.uno.test.technician.Technician_TicketSummaryTest -->
